### ISSUE TITLE
Support GitHub Enterprise

### ISSUE THREAD

**Issue by nthienan** [wangyoucao577/assets-uploader#18]
Hi there,

Thanks for developing this useful tool. I am using GitHub Enterprise (GHE) and would like to use this. However, I encounter an issue where it tries to make API calls to `github.com` instead of my GHE. I don't find any flags to specify the GHE domain or URL. It'd be great if you could support this case.

**Comment by wangyoucao577** [comment]
It seems that use https://pkg.go.dev/github.com/google/go-github/github#NewEnterpriseClient instead of the default https://pkg.go.dev/github.com/google/go-github/github#NewClient will be good to go. Would you please have a try since I don't have a GHE to test. PR is weclome if it's ok!
